apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.2
api:
  advertiseAddress: 11.11.11.111
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"
apiServerExtraArgs:
  runtime-config: "api/all=true"
networking:
  podSubnet: 10.244.0.0/16
kubeProxy:
  config:
    mode: iptables
